openapi: 3.0.3
info:
  title: Code Sharing Platform HTTP API 1.x version
  description: Documentation for Code Sharing Platform HTTP API 1.x version
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:

  
