server:
  port: 8080
  error:
    include-message: always
###########################
# Datasource configuration
##########################
spring:
  datasource:
    url: jdbc:h2:file:../snippets
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
