<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link rel="stylesheet" href="/static/css/new_code.css">
    <script src="/static/js/code.js"></script>
</head>
<body>
<p><input id="time_restriction" type="text" placeholder="Time"></p>
<p><input id="views_restriction" type="text" placeholder="Views"></p>
<p><textarea id="code_snippet" placeholder="// write your code here"></textarea></p>
<p><button id="send_snippet" type="submit" onclick="send()">Submit</button></p>
</body>
</html>